name: WebPro

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2
        
  # Set up Node.js environment (optional, but useful for testing and linting)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the version of Node.js you want

      # Install dependencies (if any, e.g., for linting, testing)
      - name: Install dependencies
        run: npm install  # Assumes you have a package.json with dependencies listed
